### ISSUE TITLE
Error restarting weewx

### ISSUE THREAD

**Issue by mash55** [bakerkj/weewx-purpleair#14]
Running the latest version of weewx (4.2) on a raspberry pi with Python 2.7.13 and Python 3.5.3.
Installed pre-requisite, cloned repository and installed extension without errors. Restarting weewx results in the following error: 

Dec 23 10:50:51 nimbus python2[24216]: weewx[24216] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 81, in __init__
Dec 23 10:50:51 nimbus python2[24216]: weewx[24216] CRITICAL __main__:     ****      self.loadServices(config_dict)
Dec 23 10:50:51 nimbus python2[24216]: weewx[24216] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 153, in loadServices
Dec 23 10:50:51 nimbus python2[24216]: weewx[24216] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
Dec 23 10:50:51 nimbus python2[24216]: weewx[24216] CRITICAL __main__:     ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1093, in get_object
Dec 23 10:50:51 nimbus python2[24216]: weewx[24216] CRITICAL __main__:     ****      mod = __import__(module)
Dec 23 10:50:51 nimbus python2[24216]: weewx[24216] CRITICAL __main__:     ****    File "/usr/share/weewx/user/purpleair.py", line 58, in <module>
Dec 23 10:50:51 nimbus python2[24216]: weewx[24216] CRITICAL __main__:     ****      import requests
Dec 23 10:50:51 nimbus python2[24216]: weewx[24216] CRITICAL __main__:     ****  ImportError: No module named requests
Dec 23 10:50:51 nimbus python2[24216]: weewx[24216] CRITICAL __main__:     ****  Exiting.

Appreciate any help...

**Comment by mash55** [comment]
SOLVED:
Enthought 'pip install requests' does a lot of things, I had to use 'apt install' to get it up and running.

**Comment by bakerkj** [comment]
@mash55 glad you solved it.
