### ISSUE TITLE
Definition of pm units conflicts with WeeWX

### ISSUE THREAD

**Issue by rlmalisz** [bakerkj/weewx-purpleair#16]
The definition on line 77 of purpleair.py:

weewx.units.default_unit_label_dict['microgram_per_meter_cubed']  = '  \xc2\xb5g/m\xc2\xb3'

Makes the graph label generated by weewx's genplot.py to be a bit wonky...this is a string, and it's expecting Unicode.  Commenting this line out made the problem go away,  Discussion here in the Google group:

https://groups.google.com/g/weewx-user/c/BCSWQASW26I

--Richard

**Comment by bakerkj** [comment]
@rlmalisz I believe PR #17 fixes this issue. I have applied that. Please give the new code a shot.
