### ISSUE TITLE
Purple Air API should be used

### ISSUE THREAD

**Issue by kadaan** [bakerkj/weewx-purpleair#24]
Purple Air wants all data pulls to be through their API and using an api key: https://api.purpleair.com/

**Comment by xslima00** [comment]
As I see it already happened. Data are no longer available on www.purpleair.com/json

https://community.purpleair.com/t/discontinuation-of-the-json-and-data-json-urls/713

**Comment by nereocystis** [comment]
json is still available as a direct download from my purpleair device.
For example, where my device on my local network is PurpleAir-932c.lan
wget http://PurpleAir-932c.lan/json
returns 
`{"SensorId":"84:f3:eb:6e:93:2c","DateTime":"2022/06/01T19:05:50z","Geo":"PurpleAir-932c","Mem":19648,"memfrag":17,"memfb":16392,"memcs":840,"Id":30865,"lat":37.803101,"lon":-122.225197,"Adc":0.00,"loggingrate":15,"place":"inside","version":"7.00","uptime":1299223,"rssi":-58,"period":120,"httpsuccess":54485,"httpsends":54487,"hardwareversion":"2.0","hardwarediscovered":"2.0+BME280+PMSX003-A","current_temp_f":78,"current_humidity":36,"current_dewpoint_f":48,"pressure":1010.69,"p25aqic":"rgb(28,231,0)","pm2.5_aqi":24,"pm1_0_cf_1":3.29,"p_0_3_um":846.43,"pm2_5_cf_1":5.71,"p_0_5_um":233.14,"pm10_0_cf_1":8.05,"p_1_0_um":45.35,"pm1_0_atm":3.29,"p_2_5_um":6.10,"pm2_5_atm":5.71,"p_5_0_um":3.60,"pm10_0_atm":8.05,"p_10_0_um":0.30,"pa_latency":251,"response":201,"response_date":1654110346,"latency":312,"key1_response":200,"key1_response_date":1654110343,"key1_count":661905,"ts_latency":505,"key2_response":200,"key2_response_date":1654110344,"key2_count":661979,"ts_s_latency":489,"key1_response_b":200,"key1_response_date_b":1654110345,"key1_count_b":662000,"ts_latency_b":499,"wlstate":"Connected","status_0":2,"status_1":2,"status_2":2,"status_3":2,"status_4":2,"status_5":2,"status_6":2,"status_7":0,"status_8":2,"status_9":0,"ssid":"havenbmedia-wifi"}`

**Comment by xslima00** [comment]
Hello, yes. If you are accessing your device locally there is no change for you. Since I have my machine on google cloud, I have to use purple air API so I was impacted by this change.

**Comment by bakerkj** [comment]
Thanks to @xslima00 this is now fixed in release 0.8.
