### ISSUE TITLE
TypeError due to Interval setting

### ISSUE THREAD

**Issue by chrisale** [bakerkj/weewx-purpleair#27]
I started getting a TypeError in the logs with a crash from purple air after I specified the Interval = 300 in my weewx.conf.

I hacked a fix by modifying line 282 in purpleair.py from:
if delta > self.config_dict['interval'] * 1.5:

to this:
if delta > float(self.config_dict['interval']) * 1.5:

**Comment by bakerkj** [comment]
@chrisale does this change https://github.com/bakerkj/weewx-purpleair/commit/21ba435e8b99c1a32c20a602cbe14d429455a757 fix the issue for you?

**Comment by bakerkj** [comment]
Assuming this is resolved.
