### ISSUE TITLE
Limit amount of requested fields for PurpleAir API call

### ISSUE THREAD

**Issue by xslima00** [bakerkj/weewx-purpleair#28]
PurpleAir started to use "point" system to limit amount of API calls for their services. New user will receive amount of points and must buy new once spent them. Every call will consume some amount of points based on fields which are requested. It´s wise to use only fields which are stored into database and limit them in API calls.

Details about pricing are visibile [here](https://community.purpleair.com/t/api-pricing/4523).
If you use currently API calls you can see amount of consumed points [here](https://develop.purpleair.com/) and "price" of fields [here](https://develop.purpleair.com/pricing).

Based on current code only following fields are needed (maybe even less based on location of sensor):
- temperature
- humidity
- pressure
- last_seen
- pm1.0_cf_1_a
- pm1.0_cf_1_b
- pm1.0_atm_a
- pm1.0_atm_b
- pm2.5_cf_1_a
- pm2.5_cf_1_b
- pm2.5_atm_a
- pm2.5_atm_b
- pm10.0_cf_1_a
- pm10.0_cf_1_b
- pm10.0_atm_a
- pm10.0_atm_b

**Comment by bakerkj** [comment]
Thanks @xslima00! Integrated; pushed a new release.
