### ISSUE TITLE
Color is incorrect at thresholds

### ISSUE THREAD

**Issue by n7qnm** [bakerkj/weewx-purpleair#32]
Hi - not 100% sure what's going on; this does seem repeatable - when our air quality gets between 49 and 51, either rising or falling, the aqi-color gets messed up.   For example, a few loops ago, the quality is reading 51 and the color is 11195562.666666666, which works out to something between purple and green.   A few before that and 49, it was magenta.  The current loop is 10079283.2, a lighter purple,

Once it gets above 51, or below 49 it seems to settle out.

I looked at the code and couldn't see anything obvious, although as I think about it, perhaps value before the shifts needs an integer type cast. I'll try that and let you know

**Comment by bakerkj** [comment]
Please keep us posted about what you find.

**Comment by n7qnm** [comment]
My bad - I'm using weewx-purple - sorry

**Comment by bakerkj** [comment]
@n7qnm - hah - no worries!
