### ISSUE TITLE
Default installation - nothing going into /var/lib/purpleair.sdb

### ISSUE THREAD

**Issue by grajohnt** [bakerkj/weewx-purpleair#8]
With nothing other than the default installation (on a raspberry pi), nothing is being added to purpleair.sdb. File size stays the same over time, and there's no data in any of the tables.

Things seem to be working properly with no errors in syslog - lines like this below are typical:
`May  1 19:55:28 raspberrypi weewx[17738]: purpleair: 'pm1_0_cf_1_b'`

weewx.conf seems reasonable with default values for everything other than the ip of the PurpleAir sensor.

Any ideas of what to try/check next?

**Comment by bakerkj** [comment]
I'm sorry I didn't get back to you earlier. Have you had any luck since?

**Comment by grajohnt** [comment]
No problem at all!

My end goal was to get measurements into InfluxDB, but I found a way to get my weather station in there directly, and then also found the JSON end points on the PurpleAir so I could feed it in directly. This cut out a lot of complexity, and solved the problem.

Thanks for making the package available, though!
